### PR TITLE
upgrade django and removed old requirements. Changed gravatar hard co…

### PR DESCRIPTION
**Pull request by mbstacy**
upgrade django and removed old requirements. Changed gravatar hard coded http to request.schema to accomodate https

### CODE REVIEW

**Comment by tdpearson** [comment]
getting an error on first run related to mongo authentication - looks related to position of mongo user creation in cybercom_up. Testing...

**Comment by tdpearson** [comment]
@mbstacy, run against a fresh instance of cookiecutter dev branch. I made a change there which fixed the error I saw here.

**Comment by mbstacy** [comment]
Did you also test the dev branch of cybercom-api (rebuild api container  docker build -t api .) Then run with clean version of cookiecutter. If that checks out, please accept and merge to master!

**Comment by tdpearson** [comment]
Checked out and confirmed

**Pull request merged**
